name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instalar dependencias
        run: bun install --frozen-lockfile

      - name: Compilar proyecto
        run: bun run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
